# Generated by Django 3.2.25 on 2026-09-22 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0025_alter_transformer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPolicy',
            fields=[
                ('policy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policyengine.policy')),
                ('script_code', models.TextField(blank=True, default='')),
            ],
            bases=('policyengine.policy',),
        ),
    ]
