# Generated by Django 3.2.25 on 2026-09-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyengine', '0026_generatedpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpolicy',
            name='handler_registry',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generatedpolicy',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScheduledCallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('function_name', models.CharField(max_length=255)),
                ('args', models.JSONField(default=list)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_callbacks', to='policyengine.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyStoreEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_entries', to='policyengine.policy')),
            ],
        ),
        migrations.AddIndex(
            model_name='scheduledcallback',
            index=models.Index(fields=['fired_at', 'run_at'], name='policyengin_fired_a_b821a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policystoreentry',
            unique_together={('policy', 'key')},
        ),
    ]
